// <auto-generated />
#pragma warning disable 1570, 1591

using System;
using Microsoft.ML.Probabilistic;
using Microsoft.ML.Probabilistic.Distributions;
using Microsoft.ML.Probabilistic.Factors;

namespace Models
{
	/// <summary>
	/// Generated algorithm for performing inference.
	/// </summary>
	/// <remarks>
	/// If you wish to use this class directly, you must perform the following steps:
	/// 1) Create an instance of the class.
	/// 2) Set the value of any externally-set fields e.g. data, priors.
	/// 3) Call the Execute(numberOfIterations) method.
	/// 4) Use the XXXMarginal() methods to retrieve posterior marginals for different variables.
	/// 
	/// Generated by Infer.NET 0.3.1810.501 at 7:39 PM on November 11, 2019.
	/// </remarks>
	public partial class Model0_EP : IGeneratedAlgorithm
	{
		#region Fields
		/// <summary>True if Changed_t7 has executed. Set this to false to force re-execution of Changed_t7</summary>
		public bool Changed_t7_isDone;
		/// <summary>Field backing the NumberOfIterationsDone property</summary>
		private int numberOfIterationsDone;
		/// <summary>Message to marginal of 't1'</summary>
		public Gaussian t1_marginal_F;
		/// <summary>Message to marginal of 't2'</summary>
		public Gaussian t2_marginal_F;
		/// <summary>Message to marginal of 't4'</summary>
		public Gaussian t4_marginal_F;
		/// <summary>Message to marginal of 't5'</summary>
		public Gaussian t5_marginal_F;
		/// <summary>Field backing the t7 property</summary>
		private double T7;
		public Gaussian t7_marginal;
		/// <summary>Message to marginal of 'vdouble10'</summary>
		public Gaussian vdouble10_marginal_F;
		/// <summary>Message to marginal of 'vdouble6'</summary>
		public Gaussian vdouble6_marginal_F;
		#endregion

		#region Properties
		/// <summary>The number of iterations done from the initial state</summary>
		public int NumberOfIterationsDone
		{
			get {
				return this.numberOfIterationsDone;
			}
		}

		/// <summary>The externally-specified value of 't7'</summary>
		public double t7
		{
			get {
				return this.T7;
			}
			set {
				if (this.T7!=value) {
					this.T7 = value;
					this.numberOfIterationsDone = 0;
					this.Changed_t7_isDone = false;
				}
			}
		}

		#endregion

		#region Methods
		/// <summary>Computations that depend on the observed value of t7</summary>
		private void Changed_t7()
		{
			if (this.Changed_t7_isDone) {
				return ;
			}
			this.t7_marginal = Gaussian.Uniform();
			this.t7_marginal = Distribution.SetPoint<Gaussian,double>(this.t7_marginal, this.T7);
			Gaussian t1_F = default(Gaussian);
			this.t1_marginal_F = Gaussian.Uniform();
			Gaussian t1_use_B = Gaussian.Uniform();
			// Message to 't1' from GaussianFromMeanAndVariance factor
			t1_F = GaussianFromMeanAndVarianceOp.SampleAverageConditional(1.0, 1.0);
			Gaussian[] t1_uses_F;
			Gaussian[] t1_uses_B;
			// Create array for 't1_uses' Forwards messages.
			t1_uses_F = new Gaussian[2];
			// Create array for 't1_uses' Backwards messages.
			t1_uses_B = new Gaussian[2];
			t1_uses_B[1] = Gaussian.Uniform();
			t1_uses_B[0] = Gaussian.Uniform();
			t1_uses_F[1] = Gaussian.Uniform();
			t1_uses_F[0] = Gaussian.Uniform();
			Gaussian t2_F = default(Gaussian);
			// Message to 't2' from GaussianFromMeanAndVariance factor
			t2_F = GaussianFromMeanAndVarianceOp.SampleAverageConditional(10.0, 1.0);
			Gaussian[] t2_uses_B;
			// Create array for 't2_uses' Backwards messages.
			t2_uses_B = new Gaussian[2];
			t2_uses_B[1] = Gaussian.Uniform();
			Gaussian[] t2_uses_F;
			// Create array for 't2_uses' Forwards messages.
			t2_uses_F = new Gaussian[2];
			t2_uses_F[0] = Gaussian.Uniform();
			// Message to 't2_uses' from Replicate factor
			t2_uses_F[0] = ReplicateOp_NoDivide.UsesAverageConditional<Gaussian>(t2_uses_B, t2_F, 0, t2_uses_F[0]);
			// Message to 't1_uses' from Replicate factor
			t1_uses_F[0] = ReplicateOp_NoDivide.UsesAverageConditional<Gaussian>(t1_uses_B, t1_F, 0, t1_uses_F[0]);
			Gaussian vdouble6_F = default(Gaussian);
			// Message to 'vdouble6' from Plus factor
			vdouble6_F = DoublePlusOp.SumAverageConditional(t1_uses_F[0], t2_uses_F[0]);
			Gaussian t4_F = default(Gaussian);
			// Message to 't4' from GaussianFromMeanAndVariance factor
			t4_F = GaussianFromMeanAndVarianceOp.SampleAverageConditional(2.0, 1.0);
			Gaussian[] t4_uses_B;
			// Create array for 't4_uses' Backwards messages.
			t4_uses_B = new Gaussian[2];
			t4_uses_B[0] = Gaussian.Uniform();
			Gaussian[] t4_uses_F;
			// Create array for 't4_uses' Forwards messages.
			t4_uses_F = new Gaussian[2];
			t4_uses_F[1] = Gaussian.Uniform();
			// Message to 't4_uses' from Replicate factor
			t4_uses_F[1] = ReplicateOp_NoDivide.UsesAverageConditional<Gaussian>(t4_uses_B, t4_F, 1, t4_uses_F[1]);
			Gaussian vdouble6_use_B = default(Gaussian);
			// Message to 'vdouble6_use' from Product factor
			vdouble6_use_B = GaussianProductOp.AAverageConditional(this.T7, vdouble6_F, t4_uses_F[1]);
			// Message to 't1_uses' from Plus factor
			t1_uses_B[0] = DoublePlusOp.AAverageConditional(vdouble6_use_B, t2_uses_F[0]);
			// Message to 't1_use' from Replicate factor
			t1_use_B = ReplicateOp_NoDivide.DefAverageConditional<Gaussian>(t1_uses_B, t1_use_B);
			// Message to 't1_marginal' from Variable factor
			this.t1_marginal_F = VariableOp.MarginalAverageConditional<Gaussian>(t1_use_B, t1_F, this.t1_marginal_F);
			// Message to 't1_uses' from Replicate factor
			t1_uses_F[1] = ReplicateOp_NoDivide.UsesAverageConditional<Gaussian>(t1_uses_B, t1_F, 1, t1_uses_F[1]);
			this.t2_marginal_F = Gaussian.Uniform();
			Gaussian t2_use_B = Gaussian.Uniform();
			t2_uses_B[0] = Gaussian.Uniform();
			t2_uses_F[1] = Gaussian.Uniform();
			// Message to 't2_uses' from Plus factor
			t2_uses_B[0] = DoublePlusOp.BAverageConditional(vdouble6_use_B, t1_uses_F[0]);
			// Message to 't2_use' from Replicate factor
			t2_use_B = ReplicateOp_NoDivide.DefAverageConditional<Gaussian>(t2_uses_B, t2_use_B);
			// Message to 't2_marginal' from Variable factor
			this.t2_marginal_F = VariableOp.MarginalAverageConditional<Gaussian>(t2_use_B, t2_F, this.t2_marginal_F);
			// Message to 't2_uses' from Replicate factor
			t2_uses_F[1] = ReplicateOp_NoDivide.UsesAverageConditional<Gaussian>(t2_uses_B, t2_F, 1, t2_uses_F[1]);
			this.vdouble6_marginal_F = Gaussian.Uniform();
			// Message to 'vdouble6_marginal' from DerivedVariable factor
			this.vdouble6_marginal_F = DerivedVariableOp.MarginalAverageConditional<Gaussian>(vdouble6_use_B, vdouble6_F, this.vdouble6_marginal_F);
			this.t4_marginal_F = Gaussian.Uniform();
			Gaussian t4_use_B = Gaussian.Uniform();
			t4_uses_B[1] = Gaussian.Uniform();
			t4_uses_F[0] = Gaussian.Uniform();
			// Message to 't4_uses' from Product factor
			t4_uses_B[1] = GaussianProductOp.BAverageConditional(this.T7, vdouble6_F, t4_uses_F[1]);
			// Message to 't4_use' from Replicate factor
			t4_use_B = ReplicateOp_NoDivide.DefAverageConditional<Gaussian>(t4_uses_B, t4_use_B);
			// Message to 't4_marginal' from Variable factor
			this.t4_marginal_F = VariableOp.MarginalAverageConditional<Gaussian>(t4_use_B, t4_F, this.t4_marginal_F);
			// Message to 't4_uses' from Replicate factor
			t4_uses_F[0] = ReplicateOp_NoDivide.UsesAverageConditional<Gaussian>(t4_uses_B, t4_F, 0, t4_uses_F[0]);
			Gaussian vdouble10_F = default(Gaussian);
			this.vdouble10_marginal_F = Gaussian.Uniform();
			Gaussian vdouble10_use_B = Gaussian.Uniform();
			// Message to 'vdouble10' from Plus factor
			vdouble10_F = DoublePlusOp.SumAverageConditional(t1_uses_F[1], t2_uses_F[1]);
			// Message to 'vdouble10_marginal' from DerivedVariable factor
			this.vdouble10_marginal_F = DerivedVariableOp.MarginalAverageConditional<Gaussian>(vdouble10_use_B, vdouble10_F, this.vdouble10_marginal_F);
			Gaussian t5_F = default(Gaussian);
			this.t5_marginal_F = Gaussian.Uniform();
			Gaussian t5_use_B = Gaussian.Uniform();
			// Message to 't5' from Product factor
			t5_F = GaussianProductOp.ProductAverageConditional(t5_use_B, vdouble10_F, t4_uses_F[0]);
			// Message to 't5_marginal' from DerivedVariable factor
			this.t5_marginal_F = DerivedVariableOp.MarginalAverageConditional<Gaussian>(t5_use_B, t5_F, this.t5_marginal_F);
			this.Changed_t7_isDone = true;
		}

		/// <summary>Update all marginals, by iterating message passing the given number of times</summary>
		/// <param name="numberOfIterations">The number of times to iterate each loop</param>
		/// <param name="initialise">If true, messages that initialise loops are reset when observed values change</param>
		private void Execute(int numberOfIterations, bool initialise)
		{
			this.Changed_t7();
			this.numberOfIterationsDone = numberOfIterations;
		}

		/// <summary>Update all marginals, by iterating message-passing the given number of times</summary>
		/// <param name="numberOfIterations">The total number of iterations that should be executed for the current set of observed values.  If this is more than the number already done, only the extra iterations are done.  If this is less than the number already done, message-passing is restarted from the beginning.  Changing the observed values resets the iteration count to 0.</param>
		public void Execute(int numberOfIterations)
		{
			this.Execute(numberOfIterations, true);
		}

		/// <summary>Get the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		public object GetObservedValue(string variableName)
		{
			if (variableName=="t7") {
				return this.t7;
			}
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName)
		{
			if (variableName=="t7") {
				return this.T7Marginal();
			}
			if (variableName=="t1") {
				return this.T1Marginal();
			}
			if (variableName=="t2") {
				return this.T2Marginal();
			}
			if (variableName=="vdouble6") {
				return this.Vdouble6Marginal();
			}
			if (variableName=="t4") {
				return this.T4Marginal();
			}
			if (variableName=="vdouble10") {
				return this.Vdouble10Marginal();
			}
			if (variableName=="t5") {
				return this.T5Marginal();
			}
			throw new ArgumentException("This class was not built to infer "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName));
		}

		/// <summary>Get the query-specific marginal distribution of a variable.</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName, string query)
		{
			if (query=="Marginal") {
				return this.Marginal(variableName);
			}
			throw new ArgumentException(((("This class was not built to infer \'"+variableName)+"\' with query \'")+query)+"\'");
		}

		/// <summary>Get the query-specific marginal distribution of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName, string query)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName, query));
		}

		private void OnProgressChanged(ProgressChangedEventArgs e)
		{
			// Make a temporary copy of the event to avoid a race condition
			// if the last subscriber unsubscribes immediately after the null check and before the event is raised.
			EventHandler<ProgressChangedEventArgs> handler = this.ProgressChanged;
			if (handler!=null) {
				handler(this, e);
			}
		}

		/// <summary>Reset all messages to their initial values.  Sets NumberOfIterationsDone to 0.</summary>
		public void Reset()
		{
			this.Execute(0);
		}

		/// <summary>Set the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		/// <param name="value">Observed value</param>
		public void SetObservedValue(string variableName, object value)
		{
			if (variableName=="t7") {
				this.t7 = (double)value;
				return ;
			}
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>
		/// Returns the marginal distribution for 't1' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Gaussian T1Marginal()
		{
			return this.t1_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 't2' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Gaussian T2Marginal()
		{
			return this.t2_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 't4' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Gaussian T4Marginal()
		{
			return this.t4_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 't5' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Gaussian T5Marginal()
		{
			return this.t5_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 't7' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Gaussian T7Marginal()
		{
			return this.t7_marginal;
		}

		/// <summary>Update all marginals, by iterating message-passing an additional number of times</summary>
		/// <param name="additionalIterations">The number of iterations that should be executed, starting from the current message state.  Messages are not reset, even if observed values have changed.</param>
		public void Update(int additionalIterations)
		{
			this.Execute(checked(this.numberOfIterationsDone+additionalIterations), false);
		}

		/// <summary>
		/// Returns the marginal distribution for 'vdouble10' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Gaussian Vdouble10Marginal()
		{
			return this.vdouble10_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vdouble6' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Gaussian Vdouble6Marginal()
		{
			return this.vdouble6_marginal_F;
		}

		#endregion

		#region Events
		/// <summary>Event that is fired when the progress of inference changes, typically at the end of one iteration of the inference algorithm.</summary>
		public event EventHandler<ProgressChangedEventArgs> ProgressChanged;
		#endregion

	}

}
