// <auto-generated />
#pragma warning disable 1570, 1591

using System;
using Microsoft.ML.Probabilistic;
using Microsoft.ML.Probabilistic.Distributions;
using Microsoft.ML.Probabilistic.Factors;

namespace Models
{
	/// <summary>
	/// Generated algorithm for performing inference.
	/// </summary>
	/// <remarks>
	/// If you wish to use this class directly, you must perform the following steps:
	/// 1) Create an instance of the class.
	/// 2) Set the value of any externally-set fields e.g. data, priors.
	/// 3) Call the Execute(numberOfIterations) method.
	/// 4) Use the XXXMarginal() methods to retrieve posterior marginals for different variables.
	/// 
	/// Generated by Infer.NET 0.3.1810.501 at 4:52 PM on November 10, 2019.
	/// </remarks>
	public partial class Model0_EP : IGeneratedAlgorithm
	{
		#region Fields
		/// <summary>True if Changed_t5 has executed. Set this to false to force re-execution of Changed_t5</summary>
		public bool Changed_t5_isDone;
		/// <summary>Field backing the NumberOfIterationsDone property</summary>
		private int numberOfIterationsDone;
		/// <summary>Message to marginal of 't1'</summary>
		public Gaussian t1_marginal_F;
		/// <summary>Message to marginal of 't2'</summary>
		public Gaussian t2_marginal_F;
		/// <summary>Message to marginal of 't4'</summary>
		public Gaussian t4_marginal_F;
		/// <summary>Field backing the t5 property</summary>
		private double T5;
		public Gaussian t5_marginal;
		/// <summary>Message to marginal of 'vdouble9'</summary>
		public Gaussian vdouble9_marginal_F;
		#endregion

		#region Properties
		/// <summary>The number of iterations done from the initial state</summary>
		public int NumberOfIterationsDone
		{
			get {
				return this.numberOfIterationsDone;
			}
		}

		/// <summary>The externally-specified value of 't5'</summary>
		public double t5
		{
			get {
				return this.T5;
			}
			set {
				if (this.T5!=value) {
					this.T5 = value;
					this.numberOfIterationsDone = 0;
					this.Changed_t5_isDone = false;
				}
			}
		}

		#endregion

		#region Methods
		/// <summary>Computations that depend on the observed value of t5</summary>
		private void Changed_t5()
		{
			if (this.Changed_t5_isDone) {
				return ;
			}
			this.t5_marginal = Gaussian.Uniform();
			this.t5_marginal = Distribution.SetPoint<Gaussian,double>(this.t5_marginal, this.T5);
			Gaussian t1_F = default(Gaussian);
			this.t1_marginal_F = Gaussian.Uniform();
			Gaussian t1_use_B = default(Gaussian);
			// Message to 't1' from GaussianFromMeanAndVariance factor
			t1_F = GaussianFromMeanAndVarianceOp.SampleAverageConditional(1.0, 1.0);
			Gaussian t2_F = default(Gaussian);
			// Message to 't2' from GaussianFromMeanAndVariance factor
			t2_F = GaussianFromMeanAndVarianceOp.SampleAverageConditional(10.0, 1.0);
			Gaussian t4_F = default(Gaussian);
			// Message to 't4' from GaussianFromMeanAndVariance factor
			t4_F = GaussianFromMeanAndVarianceOp.SampleAverageConditional(2.0, 1.0);
			Gaussian vdouble9_F = default(Gaussian);
			// Message to 'vdouble9' from Plus factor
			vdouble9_F = DoublePlusOp.SumAverageConditional(t1_F, t2_F);
			Gaussian vdouble9_use_B = default(Gaussian);
			// Message to 'vdouble9_use' from Product factor
			vdouble9_use_B = GaussianProductOp.AAverageConditional(this.T5, vdouble9_F, t4_F);
			// Message to 't1_use' from Plus factor
			t1_use_B = DoublePlusOp.AAverageConditional(vdouble9_use_B, t2_F);
			// Message to 't1_marginal' from Variable factor
			this.t1_marginal_F = VariableOp.MarginalAverageConditional<Gaussian>(t1_use_B, t1_F, this.t1_marginal_F);
			this.t2_marginal_F = Gaussian.Uniform();
			Gaussian t2_use_B = default(Gaussian);
			// Message to 't2_use' from Plus factor
			t2_use_B = DoublePlusOp.BAverageConditional(vdouble9_use_B, t1_F);
			// Message to 't2_marginal' from Variable factor
			this.t2_marginal_F = VariableOp.MarginalAverageConditional<Gaussian>(t2_use_B, t2_F, this.t2_marginal_F);
			this.t4_marginal_F = Gaussian.Uniform();
			Gaussian t4_use_B = default(Gaussian);
			// Message to 't4_use' from Product factor
			t4_use_B = GaussianProductOp.BAverageConditional(this.T5, vdouble9_F, t4_F);
			// Message to 't4_marginal' from Variable factor
			this.t4_marginal_F = VariableOp.MarginalAverageConditional<Gaussian>(t4_use_B, t4_F, this.t4_marginal_F);
			this.vdouble9_marginal_F = Gaussian.Uniform();
			// Message to 'vdouble9_marginal' from DerivedVariable factor
			this.vdouble9_marginal_F = DerivedVariableOp.MarginalAverageConditional<Gaussian>(vdouble9_use_B, vdouble9_F, this.vdouble9_marginal_F);
			this.Changed_t5_isDone = true;
		}

		/// <summary>Update all marginals, by iterating message passing the given number of times</summary>
		/// <param name="numberOfIterations">The number of times to iterate each loop</param>
		/// <param name="initialise">If true, messages that initialise loops are reset when observed values change</param>
		private void Execute(int numberOfIterations, bool initialise)
		{
			this.Changed_t5();
			this.numberOfIterationsDone = numberOfIterations;
		}

		/// <summary>Update all marginals, by iterating message-passing the given number of times</summary>
		/// <param name="numberOfIterations">The total number of iterations that should be executed for the current set of observed values.  If this is more than the number already done, only the extra iterations are done.  If this is less than the number already done, message-passing is restarted from the beginning.  Changing the observed values resets the iteration count to 0.</param>
		public void Execute(int numberOfIterations)
		{
			this.Execute(numberOfIterations, true);
		}

		/// <summary>Get the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		public object GetObservedValue(string variableName)
		{
			if (variableName=="t5") {
				return this.t5;
			}
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName)
		{
			if (variableName=="t5") {
				return this.T5Marginal();
			}
			if (variableName=="t1") {
				return this.T1Marginal();
			}
			if (variableName=="t2") {
				return this.T2Marginal();
			}
			if (variableName=="t4") {
				return this.T4Marginal();
			}
			if (variableName=="vdouble9") {
				return this.Vdouble9Marginal();
			}
			throw new ArgumentException("This class was not built to infer "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName));
		}

		/// <summary>Get the query-specific marginal distribution of a variable.</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName, string query)
		{
			if (query=="Marginal") {
				return this.Marginal(variableName);
			}
			throw new ArgumentException(((("This class was not built to infer \'"+variableName)+"\' with query \'")+query)+"\'");
		}

		/// <summary>Get the query-specific marginal distribution of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName, string query)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName, query));
		}

		private void OnProgressChanged(ProgressChangedEventArgs e)
		{
			// Make a temporary copy of the event to avoid a race condition
			// if the last subscriber unsubscribes immediately after the null check and before the event is raised.
			EventHandler<ProgressChangedEventArgs> handler = this.ProgressChanged;
			if (handler!=null) {
				handler(this, e);
			}
		}

		/// <summary>Reset all messages to their initial values.  Sets NumberOfIterationsDone to 0.</summary>
		public void Reset()
		{
			this.Execute(0);
		}

		/// <summary>Set the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		/// <param name="value">Observed value</param>
		public void SetObservedValue(string variableName, object value)
		{
			if (variableName=="t5") {
				this.t5 = (double)value;
				return ;
			}
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>
		/// Returns the marginal distribution for 't1' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Gaussian T1Marginal()
		{
			return this.t1_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 't2' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Gaussian T2Marginal()
		{
			return this.t2_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 't4' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Gaussian T4Marginal()
		{
			return this.t4_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 't5' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Gaussian T5Marginal()
		{
			return this.t5_marginal;
		}

		/// <summary>Update all marginals, by iterating message-passing an additional number of times</summary>
		/// <param name="additionalIterations">The number of iterations that should be executed, starting from the current message state.  Messages are not reset, even if observed values have changed.</param>
		public void Update(int additionalIterations)
		{
			this.Execute(checked(this.numberOfIterationsDone+additionalIterations), false);
		}

		/// <summary>
		/// Returns the marginal distribution for 'vdouble9' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Gaussian Vdouble9Marginal()
		{
			return this.vdouble9_marginal_F;
		}

		#endregion

		#region Events
		/// <summary>Event that is fired when the progress of inference changes, typically at the end of one iteration of the inference algorithm.</summary>
		public event EventHandler<ProgressChangedEventArgs> ProgressChanged;
		#endregion

	}

}
